name: Build on PlatformIO and test on Wokwi

on:
  workflow_dispatch:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run

      - name: Static Analysis with PlatformIO Project
        run: pio check

      # Optional
      # NOTE: Ignore this option when it starts charging
      - name: Test with Wokwi
        uses: wokwi/wokwi-ci-action@v1
        with:
          # Remember to define the token in secrets
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          # Define the test case(s)
          scenario: 'test/wokwi/template.test.yaml'